/**
 * README strings.
 *
 * English only for now — unlike the Seedance repos this one does not ship
 * translated READMEs, so there is one table and `t()` ignores the locale
 * argument except for date formatting. Keeping the same shape as those repos
 * means the markdown generator needs no changes if translations are added.
 */
export interface Translation {
  title: string;
  subtitle: string;
  galleryDescription: string;
  viewInGallery: string;
  browseGallery: string;
  whatIs: string;
  whatIsContent: string;
  statistics: string;
  totalPrompts: string;
  featuredPrompts: string;
  lastUpdated: string;
  featuredSection: string;
  allPrompts: string;
  morePrompts: string;
  morePromptsContent: string;
  prompt: string;
  tips: string;
  tipsSection: string;
  author: string;
  source: string;
  published: string;
  featured: string;
  tryItNow: string;
  contributing: string;
  contributingContent: string;
  license: string;
  licenseContent: string;
  acknowledgements: string;
  acknowledgementsContent: string;
  starHistory: string;
  madeWith: string;
  copyright: string;
  imagePreview: string;
  referenceImage: string;
  tableOfContents: string;
  copyrightNotice: string;
  // Comparison table
  featureCol: string;
  githubReadmeCol: string;
  galleryCol: string;
  browsingFeature: string;
  readmeBrowsing: string;
  galleryBrowsing: string;
  searchFeature: string;
  ctrlFOnly: string;
  fuzzySearch: string;
  mobileFeature: string;
  mobileBasic: string;
  mobileResponsive: string;
  coverageFeature: string;
  readmeCoverage: string;
  galleryCoverage: string;
  // Stats table
  metricCol: string;
  countCol: string;
  tipsAndTutorials: string;
  // Prompt list
  sortedByDate: string;
  moreNotShown: string;
  // Tips section
  tipsSubtitle: string;
  andMoreTips: string;
  viewAllInGallery: string;
  // Footer
  submitPrompt: string;
  starRepo: string;
  autoGenerated: string;
  // Renoise traffic CTAs
  runItCta: string;
  runItCtaLink: string;
  exploreMore: string;
  modelPage: string;
  blogExplainer: string;
  featureGptImage2: string;
  siblingSeedance: string;
}

const en: Translation = {
  title: 'Awesome GPT Image 2.5 Prompts',
  subtitle:
    "**Text-to-image prompts for ChatGPT Images 2.5 (GPT-Image-2.5 Flare / Sunburst)** — collected from public posts where the creator shared the exact prompt next to the result, from OpenAI's own launch samples, and from open case studies. Every prompt here reproduces from the text alone: none needs a reference image, an edit of an existing picture, or a multi-turn conversation.",
  galleryDescription:
    'Browse the whole library with search, tag filters, and one-click generation',
  viewInGallery: 'View in Web Gallery',
  browseGallery: 'Browse all GPT Image 2.5 prompts on Renoise',
  whatIs: 'What is GPT Image 2.5?',
  whatIsContent: `**ChatGPT Images 2.5** is OpenAI's image model released on **September 8, 2026**. Inside ChatGPT there is no model picker — you generate an image and you are using it. In the API it ships as **two** models: **GPT-Image-2.5 Flare**, the fast one, and **GPT-Image-2.5 Sunburst**, the higher-quality one. There is no single model called \`gpt-image-2.5\`.

**What changed versus GPT Image 2 — control, not size:**

* ✏️ **Precision editing** — edits touch only what you asked for
* 🔁 **Multi-turn edits** hold up instead of drifting over rounds
* 🧍 **Reference fidelity** — subjects stay recognizable
* ⚡ **Up to 50% faster**

**What did not change:** still up to 4K, still up to 16 reference images, same 1:3 to 3:1 aspect range. OpenAI claims no improvement to text rendering.`,
  statistics: '📊 Statistics',
  totalPrompts: 'Total Prompts',
  featuredPrompts: 'Featured',
  lastUpdated: 'Last Updated',
  featuredSection: '⭐ Featured Prompts',
  allPrompts: '🖼️ All Prompts',
  morePrompts: '📚 More Prompts',
  morePromptsContent:
    'This README shows the most-liked prompts. Visit the gallery for the full collection with search and tag filters.',
  prompt: 'Prompt',
  tips: 'Tips',
  tipsSection: '💡 Usage Tips',
  author: 'Author',
  source: 'Source',
  published: 'Published',
  featured: '⭐ Featured',
  tryItNow: '👉 Try it now →',
  contributing: '🤝 Contributing',
  contributingContent:
    'The library is built from public posts, so sharing your prompt together with the image is the way in. Pull requests adding a prompt JSON file are welcome too — see the [Contributing Guide](CONTRIBUTING.md) and `data/schema.json`.',
  license: '📄 License',
  licenseContent:
    'This collection is licensed under [CC BY 4.0](LICENSE). You are free to share and adapt the prompts with attribution.',
  acknowledgements: '🙏 Acknowledgements',
  acknowledgementsContent:
    'Thanks to every creator who published their prompt alongside the result, to OpenAI for the launch sample set, and to the open case-study repositories this collection draws on. Each prompt links back to its source.',
  starHistory: '⭐ Star History',
  madeWith: 'Made with ❤️ by',
  copyright: '© 2026 Renoise. All rights reserved.',
  imagePreview: 'Generated image',
  referenceImage: 'Reference Image',
  tableOfContents: 'Table of Contents',
  copyrightNotice:
    'Notice: prompts and images are collected from public posts, credited to their authors, and shared here for educational and demonstration purposes. If you believe any content infringes on your rights, please open an issue and we will remove it promptly.',
  featureCol: 'Feature',
  githubReadmeCol: 'GitHub README',
  galleryCol: 'Gallery',
  browsingFeature: '🖼️ Browsing',
  readmeBrowsing: 'One long page',
  galleryBrowsing: 'Masonry grid, full prompt one click away',
  searchFeature: '🔍 Search',
  ctrlFOnly: 'Ctrl+F on this page',
  fuzzySearch: 'Searches the whole library',
  mobileFeature: '📱 Mobile',
  mobileBasic: 'Basic',
  mobileResponsive: 'Fully responsive',
  coverageFeature: '📚 Coverage',
  readmeCoverage: 'Top 100',
  galleryCoverage: 'Every prompt, loaded as you scroll',
  metricCol: 'Metric',
  countCol: 'Count',
  tipsAndTutorials: 'Tips & Tutorials',
  sortedByDate: 'Sorted by publish date (newest first)',
  moreNotShown: 'more prompts not shown here',
  tipsSubtitle: 'Tips for getting the most out of GPT Image 2.5',
  andMoreTips: 'and {n} more tips.',
  viewAllInGallery: 'View all in Gallery',
  submitPrompt: 'Submit a Prompt',
  starRepo: 'Star this repo',
  autoGenerated: 'This README is automatically generated. Last updated:',
  runItCta: '💡 **Copy any prompt and {link}** — no setup, no install.',
  runItCtaLink: 'run it instantly in Renoise →',
  exploreMore: '🚀 Explore more on Renoise',
  modelPage: 'GPT Image 2.5 model',
  blogExplainer: 'What Images 2.5 actually changed',
  featureGptImage2: 'GPT Image 2',
  siblingSeedance: 'Seedance 2.5 prompts',
};

const I18N: Record<string, Translation> = { en };

export function t(key: keyof Translation, locale: string): string {
  const lang = I18N[locale] || en;
  return lang[key] || en[key] || key;
}

const DATE_LOCALES: Record<string, string> = { en: 'en-US' };

export function formatDateLocalized(iso: string | undefined, locale: string): string {
  if (!iso) return 'N/A';
  const dateLocale = DATE_LOCALES[locale] || 'en-US';
  return new Date(iso).toLocaleDateString(dateLocale, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}
